
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv Paul
 */
public class Admin extends javax.swing.JFrame {

    public static String name,userid;
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        
        
    }

    public Admin(String usern, String nm) {
        try {
            initComponents();
            Ndisplay.setText(""+nm);
            name=nm;
            userid=usern;
            Hbd.setVisible(false);
            String fulldt="",full,dt="",mon="",y="",hbddt="";
            char temp=' ';
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            full =cal.getTime().toString();
            for(int i=8;i<=9;i++) {
                temp = full.charAt(i);
                dt += temp;
            }
            fulldt= fulldt+dt+"-";
            for(int i=4;i<=6;i++) {
                temp =  full.charAt(i);
                mon += temp;
            }
            hbddt=fulldt+mon;
            fulldt= fulldt+mon+"-";
            for(int i=24;i<=27;i++) {
                temp =  full.charAt(i);
                y += temp;
            }
            fulldt= fulldt+y;
            ResultSet rs= stat.executeQuery("select * from attendance where loginid='"+userid+"' and adate='"+fulldt+"'");
            if (rs.next()) {
                AttendanceL.setText("YES");
            } else {
                AttendanceL.setText("NO");
            }
            rs = stat.executeQuery("select dob from details where loginid='"+userid+"'");
            if (rs.next()) {
                String dob="",dobc;
                dob=rs.getString(1);
                int m;
                dt="";
                mon="";
                for(int i=8;i<=9;i++) {
                    temp= dob.charAt(i);
                    dt += temp;
                }
                dobc=dt+"-";
                for(int i=5;i<=6;i++) {
                    temp= dob.charAt(i);
                    mon += temp;
                }
                m=Integer.parseInt(mon);
                if (mon.equals("08")) {
                    mon= "Aug";
                } else if (mon.equals("09")) {
                    mon= "Sep";
                } else {
                    switch (m) {
                    case 01 : mon="Jan";
                                break;
                    case 02 :   mon="Feb";
                                break;
                    case 03 :   mon="Mar";
                                break;
                    case 04 :   mon="Apr";
                                break;
                    case 05 :   mon="May";
                                break;
                    case 06 :   mon="Jun";
                                break;
                    case 07 :   mon="Jul";
                                break;
                    case 10 :   mon="Oct";
                                break;
                    case 11 :   mon="Nov";
                                break;
                    case 12 :   mon="Dec";
                                break;
                    }   
                }
                dobc=dobc+mon;
                if (dobc.equalsIgnoreCase(hbddt)) {
                    Hbd.setText("Happy Birthday !!");
                    Hbd.setVisible(true);
                }
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addremoveuser = new javax.swing.JButton();
        WelcomeL = new javax.swing.JLabel();
        Updateattendance = new javax.swing.JButton();
        Updateuser = new javax.swing.JButton();
        Viewusers = new javax.swing.JButton();
        Updaterequests = new javax.swing.JButton();
        logoutb = new javax.swing.JButton();
        Ndisplay = new javax.swing.JLabel();
        Changepass = new javax.swing.JButton();
        Makeattendance = new javax.swing.JButton();
        AttendanceL = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Hbd = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Addremoveuser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Addremoveuser.setText("Add/Remove User");
        Addremoveuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddremoveuserActionPerformed(evt);
            }
        });

        WelcomeL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WelcomeL.setText("Welcome ,");

        Updateattendance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Updateattendance.setText("Attendance");
        Updateattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateattendanceActionPerformed(evt);
            }
        });

        Updateuser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Updateuser.setText("Update User");
        Updateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateuserActionPerformed(evt);
            }
        });

        Viewusers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Viewusers.setText("View Users");
        Viewusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewusersActionPerformed(evt);
            }
        });

        Updaterequests.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Updaterequests.setText("Update Requests");
        Updaterequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdaterequestsActionPerformed(evt);
            }
        });

        logoutb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logoutb.setText("Logout");
        logoutb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbActionPerformed(evt);
            }
        });

        Ndisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ndisplay.setText("NDisplay");

        Changepass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Changepass.setText("Recover Password");
        Changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangepassActionPerformed(evt);
            }
        });

        Makeattendance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Makeattendance.setText("Today's Attendance");
        Makeattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeattendanceActionPerformed(evt);
            }
        });

        AttendanceL.setText("YES");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Accounts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Hbd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hbd.setForeground(new java.awt.Color(0, 102, 0));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("View Own Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ndisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Changepass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutb)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Updateattendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Addremoveuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Updateuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Makeattendance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AttendanceL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Updaterequests, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(Viewusers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(7, 7, 7))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hbd, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcomeL)
                    .addComponent(logoutb)
                    .addComponent(Ndisplay)
                    .addComponent(Changepass))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addremoveuser)
                    .addComponent(Updaterequests))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updateattendance)
                    .addComponent(Viewusers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updateuser)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(Hbd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttendanceL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Makeattendance))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateattendanceActionPerformed
        Viewattendance ob=new Viewattendance('a',""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateattendanceActionPerformed

    private void logoutbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbActionPerformed
        JOptionPane.showMessageDialog(this,"You have been successfully logged out");
        Login ob = new Login();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbActionPerformed

    private void AddremoveuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddremoveuserActionPerformed
        Addremoveuser ob= new Addremoveuser(""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddremoveuserActionPerformed

    private void ChangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangepassActionPerformed
        Changepassword ob=new Changepassword('a',""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ChangepassActionPerformed

    private void UpdateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateuserActionPerformed
        Updateuser ob=new Updateuser('a',""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateuserActionPerformed

    private void ViewusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewusersActionPerformed
        Viewuser ob=new Viewuser('a',""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewusersActionPerformed

    private void UpdaterequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdaterequestsActionPerformed
        try {
            Showrequests ob=new Showrequests('a',""+userid,""+name);
            ob.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdaterequestsActionPerformed

    private void MakeattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeattendanceActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            String full =cal.getTime().toString();
            String mon="", dd="", yy="",fulldt="";
            char temp= ' ';
            for(int i=4;i<7;i++) {
                temp=full.charAt(i);
                mon += temp;
            }   
            for(int i=8;i<10;i++) {
                temp=full.charAt(i);
                dd += temp;
            }
            for(int i=24;i<=27;i++) {
                temp=full.charAt(i);
                yy += temp;
            }   
            fulldt=dd+"-"+mon+"-"+yy;
            ResultSet rs= stat.executeQuery("select * from attendance where loginid='"+userid+"' and adate='"+fulldt+"'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(this,"Your Attendance Is Already Made");
            } else {
                stat.executeQuery("insert into attendance values('"+userid+"','"+fulldt+"')");
                JOptionPane.showMessageDialog(this,"Today's Attendance Made Successfully");
                AttendanceL.setText("YES");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MakeattendanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Accounts ob=new Accounts('a',""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Profile ob=new Profile('a',""+userid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addremoveuser;
    private javax.swing.JTextField AttendanceL;
    private javax.swing.JButton Changepass;
    private javax.swing.JLabel Hbd;
    private javax.swing.JButton Makeattendance;
    private javax.swing.JLabel Ndisplay;
    private javax.swing.JButton Updateattendance;
    private javax.swing.JButton Updaterequests;
    private javax.swing.JButton Updateuser;
    private javax.swing.JButton Viewusers;
    private javax.swing.JLabel WelcomeL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton logoutb;
    // End of variables declaration//GEN-END:variables
}
