
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv Paul
 */
public class Assignments extends javax.swing.JFrame {

    public static char chk;
    public static String userid, name;
    /**
     * Creates new form Assignments
     */
    public Assignments() {
        initComponents();
    }
    
    public Assignments(char type, String usern, String nm) {
        initComponents();
        userid=usern;
        name=nm;
        chk=type;
        UserID.setEditable(false);
        Textarea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Back = new javax.swing.JButton();
        Head = new javax.swing.JLabel();
        UserIDL = new javax.swing.JLabel();
        UserID = new javax.swing.JTextField();
        AssignmentL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textarea = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        Option = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        Help = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setText("<<Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Head.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Head.setText("Assignments");

        UserIDL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserIDL.setText("Roll No.");

        UserID.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        AssignmentL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AssignmentL.setText("Assignment");

        Textarea.setColumns(20);
        Textarea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Textarea.setRows(5);
        jScrollPane1.setViewportView(Textarea);

        Submit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Option.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Option.setText("Select An Option");

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Student", "Whole Class" }));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        Help.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Check Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addGap(82, 82, 82)
                .addComponent(Head)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserIDL)
                            .addComponent(AssignmentL)
                            .addComponent(Option))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Submit)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Head))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Option)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserIDL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Help)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(AssignmentL)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Submit)
                            .addComponent(jButton1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        String check=(String)Type.getSelectedItem();
        if(check.equalsIgnoreCase("Student")) {
           UserID.setEditable(true);
           Textarea.setEditable(true);
        } else if (check.equalsIgnoreCase("Whole Class")) {
           UserIDL.setText("Branch");
           UserID.setEditable(true);
           Textarea.setEditable(true);
        } else {
           UserID.setEditable(false);
           Textarea.setEditable(false);
        }
    }//GEN-LAST:event_TypeActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        JOptionPane.showMessageDialog(this,"CompSci - Computer\nCivil - Civil\nMechanical - Mechanical\nECE - Electronics\nElectrical - Electrical");
    }//GEN-LAST:event_HelpActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            String check=(String)Type.getSelectedItem(), username, comments;
            username=UserID.getText();
            if (username.equalsIgnoreCase(userid)) {
                JOptionPane.showMessageDialog(this,"You Cannot GIve Assignment To Yourself");
                return;
            }
            comments=Textarea.getText();
            ResultSet ag;
            Statement stat1 = con.createStatement();
            Statement stat2 = con.createStatement();
            if (check.equalsIgnoreCase("Student")) {
                ResultSet rs = stat.executeQuery("select * from details where loginid='"+username+"'");
                if (rs.next()) {
                    String dept;
                    dept=rs.getString(2);
                    ag=stat1.executeQuery("select type from login where loginid='"+username+"'");
                    if (ag.next()){
                        char temp;
                        temp=ag.getString(1).charAt(0);
                        if (temp=='s'||temp=='S') {
                            stat.executeQuery("insert into assignments(loginid,comments,status,given_by,courseanddept) values('"+username+"','"+comments+"','P','"+name+"','"+dept+"')");
                            JOptionPane.showMessageDialog(this,"Assignment Given");
                        } else {
                            JOptionPane.showMessageDialog(this,"Assignment Can Only Be Given To A Student");
                        }
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this,"Invalid UserID");
                }
            } else if (check.equalsIgnoreCase("Select")) {
                JOptionPane.showMessageDialog(this,"Select An Option");
                return;
            } else if(check.equalsIgnoreCase("Whole Class")) {
                ResultSet rs = stat.executeQuery("select * from details where COURSEANDDEPT='"+username+"'");
                if (rs.next()) {
                    rs = stat.executeQuery("select * from details where COURSEANDDEPT='"+username+"'");
                    while (rs.next()) {
                        String logid=rs.getString(1);
                        char temp=' ';
                        ag=stat1.executeQuery("select type from login where loginid='"+logid+"'");
                        if (ag.next()) {
                            temp=ag.getString(1).charAt(0);
                            if (temp=='s' || temp=='S') {
                                stat2.executeQuery("insert into assignments(loginid,comments,status,given_by,courseanddept) values('"+logid+"','"+comments+"','P','"+name+"','"+username+"')");
                            }
                        }   
                    }
                    JOptionPane.showMessageDialog(this,"Assignment Sent To The Whole Class");
                } else {
                    JOptionPane.showMessageDialog(this,"Invalid Branch");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Assignments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Teacher ob=new Teacher(""+userid, ""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Viewassignments ob=new Viewassignments('T',""+name,""+userid);
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssignmentL;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Head;
    private javax.swing.JButton Help;
    private javax.swing.JLabel Option;
    private javax.swing.JButton Submit;
    private javax.swing.JTextArea Textarea;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JTextField UserID;
    private javax.swing.JLabel UserIDL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
