
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv Paul
 */
public class Changepassword extends javax.swing.JFrame {

    public static char chk;
    public static int flag=0;
    public static String name,userid;
    /**
     * Creates new form Changepassword
     */
    public Changepassword() {
        initComponents();
    }
    
    public Changepassword(char type, String usern, String nm) {
        initComponents();
        chk=type;
        name= nm;
        userid=usern;
        Recoverpass.setVisible(false);
        Ownpass.setVisible(false);
        if (type=='a'||type=='A') {
            Recoverpass.setVisible(true);
            Ownpass.setVisible(true);
            Ownpass.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        OldpassL = new javax.swing.JLabel();
        NewpassL = new javax.swing.JLabel();
        RepassL = new javax.swing.JLabel();
        Apply = new javax.swing.JButton();
        Oldpass = new javax.swing.JTextField();
        Repass = new javax.swing.JPasswordField();
        Newpass = new javax.swing.JPasswordField();
        ChangepassL = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Recoverpass = new javax.swing.JButton();
        Ownpass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setText("<<Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        OldpassL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OldpassL.setText("Old Password");

        NewpassL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NewpassL.setText("New Password");

        RepassL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RepassL.setText("Re-type Password");

        Apply.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Apply.setText("Apply");
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });

        ChangepassL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChangepassL.setText("Change Password");

        Reset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Recoverpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Recoverpass.setText("Recover Password");
        Recoverpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoverpassActionPerformed(evt);
            }
        });

        Ownpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ownpass.setText("Own Password");
        Ownpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)
                        .addGap(50, 50, 50)
                        .addComponent(ChangepassL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Reset)
                                .addGap(18, 18, 18)
                                .addComponent(Apply))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(OldpassL)
                                            .addComponent(NewpassL)
                                            .addComponent(RepassL))
                                        .addGap(45, 45, 45))
                                    .addComponent(Ownpass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Oldpass)
                                            .addComponent(Repass)
                                            .addComponent(Newpass, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Recoverpass, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(ChangepassL))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recoverpass)
                    .addComponent(Ownpass))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldpassL)
                    .addComponent(Oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewpassL)
                    .addComponent(Newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepassL)
                    .addComponent(Repass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apply)
                    .addComponent(Reset))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        if(chk=='a'||chk=='A') {
            Admin ob=new Admin(""+userid,""+name);
            ob.setVisible(true);
            this.setVisible(false);
        } else if(chk=='t'||chk=='T') {
            Teacher ob=new Teacher(""+userid,""+name);
            ob.setVisible(true);
            this.setVisible(false);
        } else if(chk=='s'||chk=='S') {
            try {
                Student ob=new Student(""+userid,""+name);
                ob.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(Changepassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BackActionPerformed

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            String oldpass, newpass, repass,dbpass="",passc="";
            int len,i = 0;
            char type=' ', temp=' ';
            oldpass=Oldpass.getText();
            newpass=new String(Newpass.getPassword());
            repass= new String(Repass.getPassword());
            if (flag==0) {
                if(newpass.equals(repass)) {
                ResultSet rs=stat.executeQuery("select password from login where loginid='"+userid+"'");
                    if(rs.next()) {
                    dbpass = rs.getString(1);
                    }
                    len = dbpass.length();
                    while(i!=len)
                    {
                        temp = dbpass.charAt(i);
                        temp=(char) ((int) temp-2);
                        passc += temp;
                        i++;
                    }
                    if(passc.equals(oldpass)) {
                        temp = ' ';
                        passc="";
                        i=0;
                        len = newpass.length();
                        while(i!=len)
                        {
                            temp = newpass.charAt(i);
                            temp=(char) ((int) temp+2);
                            passc += temp;
                            i++;
                        }
                        stat.executeQuery("update login set password='"+passc+"' where loginid='"+userid+"'");
                        JOptionPane.showMessageDialog(this,"Password Updated");
                        BackActionPerformed(evt);
                    } else {
                            JOptionPane.showMessageDialog(this,"Wrong Old Password");
                    }
                } else {
                    JOptionPane.showMessageDialog(this,"The password you entered did not match");
                }
            } else {
                String username;
                username=oldpass;
                if(newpass.equals(repass)) {
                    temp = ' ';
                    passc="";
                    i=0;
                    len = newpass.length();
                    while(i!=len) {
                        temp = newpass.charAt(i);
                        temp=(char) ((int) temp+2);
                        passc += temp;
                        i++;
                    }
                    stat.executeQuery("update login set password='"+passc+"' where loginid='"+username+"'");
                    JOptionPane.showMessageDialog(this,"Password Updated");
                    BackActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this,"The password you entered did not match");
                }       
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Changepassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ApplyActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Oldpass.setText("");
        Repass.setText("");
        Newpass.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void OwnpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnpassActionPerformed
        Ownpass.setEnabled(false);
        Recoverpass.setEnabled(true);
        OldpassL.setText("Old Password");
        NewpassL.setText("New Password");
        RepassL.setText("Re-type Password");
        flag=0;
    }//GEN-LAST:event_OwnpassActionPerformed

    private void RecoverpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoverpassActionPerformed
        Ownpass.setEnabled(true);
        Recoverpass.setEnabled(false);
        OldpassL.setText("UserID");
        NewpassL.setText("New Password");
        RepassL.setText("Re-type Password");
        ChangepassL.setText("Recover Password");
        flag=1;
    }//GEN-LAST:event_RecoverpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Changepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JButton Back;
    private javax.swing.JLabel ChangepassL;
    private javax.swing.JPasswordField Newpass;
    private javax.swing.JLabel NewpassL;
    private javax.swing.JTextField Oldpass;
    private javax.swing.JLabel OldpassL;
    private javax.swing.JButton Ownpass;
    private javax.swing.JButton Recoverpass;
    private javax.swing.JPasswordField Repass;
    private javax.swing.JLabel RepassL;
    private javax.swing.JButton Reset;
    // End of variables declaration//GEN-END:variables
}
