
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv Paul
 */
public class Modification extends javax.swing.JFrame {

    public static char chk;
    public static int flag=0;
    public static String name,auserid;
    /**
     * Creates new form Modification
     */
    public Modification() {
        initComponents();
    }

    public Modification(String usern,String nm) {
        initComponents();
        name=nm;
        auserid=usern;
        Updatesal.setEnabled(false);
        Help.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Modification = new javax.swing.JLabel();
        Updatesal = new javax.swing.JButton();
        Updatefees = new javax.swing.JButton();
        UserIDL = new javax.swing.JLabel();
        UserID = new javax.swing.JTextField();
        NewsalL = new javax.swing.JLabel();
        Newsal = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Renewsession = new javax.swing.JButton();
        Help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setText("<<Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Modification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Modification.setText("Modification(s)");

        Updatesal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Updatesal.setText("Update Salary");
        Updatesal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatesalActionPerformed(evt);
            }
        });

        Updatefees.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Updatefees.setText("Update Fees");
        Updatefees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatefeesActionPerformed(evt);
            }
        });

        UserIDL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserIDL.setText("UserID");

        UserID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NewsalL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NewsalL.setText("Updated Salary");

        Newsal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Update.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Renewsession.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Renewsession.setText("Renew Session");
        Renewsession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewsessionActionPerformed(evt);
            }
        });

        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Updatesal, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Updatefees, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(Renewsession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(74, 74, 74)
                        .addComponent(Modification))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Update)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewsalL)
                                    .addComponent(UserIDL))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Newsal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back)
                    .addComponent(Modification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(Renewsession)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updatesal)
                    .addComponent(Updatefees))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDL)
                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewsalL)
                    .addComponent(Newsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            String userid, sal;
            userid=UserID.getText();
            sal=Newsal.getText();
            ResultSet rs = stat.executeQuery("select type,courseanddep from login where loginid='"+userid+"'");
            if (rs.next()) {
                if (flag==0) {
                    if (userid.equals(auserid)) {
                        JOptionPane.showMessageDialog(this,"You Cannot Update Your Salary");
                    } else {
			if (rs.getString(1).charAt(0)=='a'||rs.getString(1).charAt(0)=='a'||rs.getString(1).charAt(0)=='a'||rs.getString(1).charAt(0)=='a') {
                            stat.executeQuery("update details set feesorsal='"+sal+"' where loginid='"+userid+"'");
                            JOptionPane.showMessageDialog(this,"Salary for userid "+userid+" Updated to "+sal);
			} else {
                            JOptionPane.showMessageDialog(this,"Salary Option Not Available for Students");
			} 
                    }
                } else {
                    if (userid.equals(auserid)) {
                        JOptionPane.showMessageDialog(this,"Fees Option Not Available for College Staff");
                    } else {
			if (rs.getString(1).charAt(0)=='s'||rs.getString(1).charAt(0)=='S') {
                            if (rs.getString(1).equals(""+userid)) {
                                stat.executeQuery("update details set feesorsal='"+sal+"' where courseanddep='"+userid+"'");
                                JOptionPane.showMessageDialog(this,"Fees of Department "+userid+" Updated to "+sal);
                            } else {
                                JOptionPane.showMessageDialog(this,"Department Not Available");
                            }
                            
			} else {
                            JOptionPane.showMessageDialog(this,"Fees Option Available Only For Students");
			}
                    } 
                } 
            } else {
		JOptionPane.showMessageDialog(this,"Invalid UserID");
            }	
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modification.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Modification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void UpdatefeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatefeesActionPerformed
        Updatesal.setEnabled(true);
        Updatefees.setEnabled(false);
        flag=1;
        NewsalL.setText("Updated Fees");
        UserIDL.setText("Department");
        Help.setEnabled(true);
    }//GEN-LAST:event_UpdatefeesActionPerformed

    private void UpdatesalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatesalActionPerformed
        Updatefees.setEnabled(true);
        Updatesal.setEnabled(false);
        NewsalL.setText("Updated Salary");
        UserIDL.setText("UserID");
        Help.setEnabled(false);
        flag=0;
    }//GEN-LAST:event_UpdatesalActionPerformed

    private void RenewsessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewsessionActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Are You Sure You Want To Renew Session","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                stat.executeQuery("delete from saldetails");
                stat.executeQuery("delete from feesdetails");
                JOptionPane.showMessageDialog(this, "Session Renewed");
            } else {
                return;
            }    
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Modification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RenewsessionActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Accounts ob=new Accounts('a',""+auserid,""+name);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        JOptionPane.showMessageDialog(this,"CompSci - Computer\nCivil - Civil\nMechanical - Mechanical\nECE - Electronics\nElectrical - Electrical");
    }//GEN-LAST:event_HelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Help;
    private javax.swing.JLabel Modification;
    private javax.swing.JTextField Newsal;
    private javax.swing.JLabel NewsalL;
    private javax.swing.JButton Renewsession;
    private javax.swing.JButton Update;
    private javax.swing.JButton Updatefees;
    private javax.swing.JButton Updatesal;
    private javax.swing.JTextField UserID;
    private javax.swing.JLabel UserIDL;
    // End of variables declaration//GEN-END:variables
}
