
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv Paul
 */
public class Removeuser extends javax.swing.JFrame {

    public static String aduserid, adname;
    /**
     * Creates new form Removeuser
     */
    public Removeuser() {
        initComponents();
    }

    public Removeuser(String nm, String usern) {
        initComponents();
        aduserid=usern;
        adname=nm;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        RemoveuserL = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        UserIDL = new javax.swing.JLabel();
        PasswordL = new javax.swing.JLabel();
        AdminpassL = new javax.swing.JLabel();
        Removeuser = new javax.swing.JButton();
        Name = new javax.swing.JTextField();
        UserID = new javax.swing.JTextField();
        Adminpass = new javax.swing.JPasswordField();
        Splitter = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setText("<<Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        RemoveuserL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RemoveuserL.setText("Remove User");

        NameL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameL.setText("Name");

        UserIDL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserIDL.setText("UserID");

        PasswordL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordL.setText("Password");

        AdminpassL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminpassL.setText("Admin Password");

        Removeuser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Removeuser.setText("Remove User");
        Removeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveuserActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)
                        .addGap(77, 77, 77)
                        .addComponent(RemoveuserL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameL)
                            .addComponent(UserIDL)
                            .addComponent(PasswordL)
                            .addComponent(AdminpassL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Name)
                            .addComponent(UserID)
                            .addComponent(Adminpass)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Removeuser)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Splitter)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back)
                            .addComponent(RemoveuserL))
                        .addGap(37, 37, 37)
                        .addComponent(NameL))
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDL)
                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordL)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Splitter, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminpassL)
                    .addComponent(Adminpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(Removeuser)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Admin ob=new Admin(""+aduserid,""+adname);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void RemoveuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveuserActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            String dbapass="",name, pass, nmcheck, adminpass, userid, passc = "", dupass="", dapass="";
            char temp= ' ';
            int i=0,len;
            name=Name.getText();
            userid=UserID.getText();
            pass=new String(Password.getPassword());
            adminpass=new String(Adminpass.getPassword());
            ResultSet rs= stat.executeQuery("select password,name from login where loginid='"+userid+"'");
            if(rs.next())
            {
                dupass=rs.getString(1);
                nmcheck=rs.getString(2);
                
            } else {
                JOptionPane.showMessageDialog(this,"Wrong UserID");
                return;
            }
            if(nmcheck.equalsIgnoreCase(name)) {
                
            } else {
                JOptionPane.showMessageDialog(this,"Wrong Name Entered");
                return;
            }
            len = pass.length();
            while(i!=len)
            {
                temp = pass.charAt(i);
                temp=(char) ((int) temp+2);
                passc += temp;
                i++;
            }
            if(passc.equals(dupass)) {
                rs= stat.executeQuery("select password from login where loginid='"+aduserid+"'");
                if (rs.next())
                {
                    dbapass=rs.getString(1);
                }
                i=0;
                len = dbapass.length();
                passc="";
                while(i!=len)
                {
                    temp = dbapass.charAt(i);
                    temp=(char) ((int) temp-2);
                    passc += temp;
                    i++;
                }
                if(passc.equals(adminpass)) {
                    stat.executeQuery("delete feedetails where loginid='"+userid+"'");
                    stat.executeQuery("delete feehistory where loginid='"+userid+"'");
                    stat.executeQuery("delete saldetails where loginid='"+userid+"'");
                    stat.executeQuery("delete salhistory where loginid='"+userid+"'");
                    stat.executeQuery("delete modifyinfo where loginid='"+userid+"'");
                    stat.executeQuery("delete assignments where loginid='"+userid+"'");
                    stat.executeQuery("delete attendance where loginid='"+userid+"'");
                    stat.executeQuery("delete details where loginid='"+userid+"'");
                    stat.executeQuery("delete login where loginid='"+userid+"'");
                    JOptionPane.showMessageDialog(this,"User Removed");
                    Admin ob=new Admin(""+aduserid,""+adname);
                    ob.setVisible(true);
                    this.setVisible(false);
                } else {
                 JOptionPane.showMessageDialog(this,"Wrong Admin Password");   
                }
            } else {
                JOptionPane.showMessageDialog(this,"Wrong UserID Password");
            }
            
        } catch (ClassNotFoundException | SQLException ex ) {
            Logger.getLogger(Removeuser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RemoveuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Removeuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Removeuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Removeuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Removeuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Removeuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Adminpass;
    private javax.swing.JLabel AdminpassL;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameL;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordL;
    private javax.swing.JButton Removeuser;
    private javax.swing.JLabel RemoveuserL;
    private javax.swing.JSeparator Splitter;
    private javax.swing.JTextField UserID;
    private javax.swing.JLabel UserIDL;
    // End of variables declaration//GEN-END:variables
}
