
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv Paul
 */
public class Updateuser extends javax.swing.JFrame {

    public static String adname, aduserid;
    public static char type;
    /**
     * Creates new form Updateuser
     */
    public Updateuser() {
        initComponents();
    }

    public Updateuser(char temp, String usern, String nm) {
        initComponents();
        type=temp;
        adname=nm;
        aduserid=usern;
        Help.setVisible(false);
        Edit1.setVisible(false);
        Edit2.setVisible(false);
        Edit3.setVisible(false);
        Edit4.setVisible(false);
        Edit5.setVisible(false);
        Edit6.setVisible(false);
        PasswordL.setVisible(false);
        Password.setVisible(false);
        Separator2.setVisible(false);
        DetailsL.setVisible(false);
        Name.setVisible(false);
        Sex.setVisible(false);
        Dob.setVisible(false);
        Course.setVisible(false);
        Usertype.setVisible(false);
        NameL.setVisible(false);
        SexL.setVisible(false);
        DobL.setVisible(false);
        CourseL.setVisible(false);
        UsertypeL.setVisible(false);
        Separator.setVisible(false);
        Update.setVisible(false);
        FeesorsalL.setVisible(false);
        Feesorsal.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        UpdateuserL = new javax.swing.JLabel();
        UserIDL = new javax.swing.JLabel();
        UserID = new javax.swing.JTextField();
        Showdetails = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        DetailsL = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        SexL = new javax.swing.JLabel();
        UsertypeL = new javax.swing.JLabel();
        DobL = new javax.swing.JLabel();
        CourseL = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Sex = new javax.swing.JTextField();
        Usertype = new javax.swing.JTextField();
        Dob = new javax.swing.JTextField();
        Course = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        FeesorsalL = new javax.swing.JLabel();
        Feesorsal = new javax.swing.JTextField();
        PasswordL = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Separator2 = new javax.swing.JSeparator();
        Help = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        Edit2 = new javax.swing.JButton();
        Edit3 = new javax.swing.JButton();
        Edit4 = new javax.swing.JButton();
        Edit5 = new javax.swing.JButton();
        Edit6 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setText("<<Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        UpdateuserL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateuserL.setText("Update User");

        UserIDL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserIDL.setText("Enter UserID");

        UserID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Showdetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Showdetails.setText("Show Details");
        Showdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowdetailsActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        DetailsL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetailsL.setText("Deatils");

        NameL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameL.setText("Name");

        SexL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SexL.setText("Sex");

        UsertypeL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UsertypeL.setText("User Type");

        DobL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DobL.setText("D.O.B");

        CourseL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CourseL.setText("Course/Department");

        Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Sex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Usertype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsertypeActionPerformed(evt);
            }
        });

        Dob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Course.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        FeesorsalL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FeesorsalL.setText("Salary");

        Feesorsal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        PasswordL.setText("Password");

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Help.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        Edit1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit1.setText("Edit");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });

        Edit2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit2.setText("Edit");
        Edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit2ActionPerformed(evt);
            }
        });

        Edit3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit3.setText("Edit");
        Edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit3ActionPerformed(evt);
            }
        });

        Edit4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit4.setText("Edit");
        Edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit4ActionPerformed(evt);
            }
        });

        Edit5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit5.setText("Edit");
        Edit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit5ActionPerformed(evt);
            }
        });

        Edit6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edit6.setText("Help");
        Edit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameL)
                    .addComponent(SexL)
                    .addComponent(UsertypeL)
                    .addComponent(DobL)
                    .addComponent(CourseL)
                    .addComponent(FeesorsalL)
                    .addComponent(PasswordL))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Feesorsal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Dob, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usertype, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Edit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addGap(61, 61, 61))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Separator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Separator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(UserIDL)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateuserL)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Reset)
                        .addGap(18, 18, 18)
                        .addComponent(Showdetails))
                    .addComponent(UserID))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(DetailsL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(UpdateuserL))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDL)
                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset)
                    .addComponent(Showdetails))
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetailsL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameL)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexL)
                    .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsertypeL)
                    .addComponent(Usertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DobL)
                    .addComponent(Dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseL)
                    .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help)
                    .addComponent(Edit5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FeesorsalL)
                    .addComponent(Feesorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit6))
                .addGap(18, 18, 18)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordL)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsertypeActionPerformed

    private void ShowdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowdetailsActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            String name, dob="", userid, dobf="", course="",fos="";
            char sex=' ',temp= ' ', usertype;
            userid=UserID.getText();
            ResultSet rs=stat.executeQuery("select name, type from login where loginid='"+userid+"'");
            
            if (rs.next()) {
                
                name=rs.getString(1);
                usertype= rs.getString(2).charAt(0); 
                if (usertype=='s'||usertype=='S') {
                    FeesorsalL.setText("Fees");
                }
            } else {
                Edit1.setVisible(false);
                Edit2.setVisible(false);
                Edit3.setVisible(false);
                Edit4.setVisible(false);
                Edit5.setVisible(false);
                Edit6.setVisible(false);
                PasswordL.setVisible(false);
                Password.setVisible(false);
                Separator2.setVisible(false);
                Name.setVisible(false);
                Sex.setVisible(false);
                Dob.setVisible(false);
                Course.setVisible(false);
                Usertype.setVisible(false);
                NameL.setVisible(false);
                SexL.setVisible(false);
                DobL.setVisible(false);
                CourseL.setVisible(false);
                UsertypeL.setVisible(false);
                Separator.setVisible(false);
                DetailsL.setVisible(false);
                Update.setVisible(false);
                FeesorsalL.setVisible(false);
                Feesorsal.setVisible(false);
                JOptionPane.showMessageDialog(this,"Invalid UserID");
                return;
            }
            rs=stat.executeQuery("select courseanddept, sex, dob, feesorsal from details where loginid='"+userid+"'");
            if (rs.next()) {
                course=rs.getString(1);
                sex=rs.getString(2).charAt(0);
                dob=rs.getString(3);
                fos=rs.getString(4);
            }
            JOptionPane.showMessageDialog(this,"Unchanged Entry Should Be Left Unchanged");
            Help.setVisible(true);
            Edit1.setVisible(true);
            Edit2.setVisible(true);
            Edit3.setVisible(true);
            Edit4.setVisible(true);
            Edit5.setVisible(true);
            Edit6.setVisible(true);
            Name.setEditable(false);
            Sex.setEditable(false);
            Dob.setEditable(false);
            Course.setEditable(false);
            Usertype.setEditable(false);
            Feesorsal.setEditable(false);
            UserID.setEditable(false);
            Name.setText(name);
            Feesorsal.setText(fos);
            for(int t=0;t<=9;t++) {
                temp=dob.charAt(t);
                dobf += temp;
            }
            Dob.setText(dobf);
            Course.setText(course);
            if (usertype == 't' || usertype == 'T' ) {
                Usertype.setText("Teacher");
            } else if (usertype == 'a' || usertype == 'A') {
                Usertype.setText("Administrator");
            } else {
                Usertype.setText("Student");
            }
            if (sex == 'm' || sex == 'M' ) {
                Sex.setText("Male");
            } else {
                Sex.setText("Female");
            }
            PasswordL.setVisible(true);
            Password.setVisible(true);
            Separator2.setVisible(true);
            DetailsL.setVisible(true);
            Name.setVisible(true);
            Sex.setVisible(true);
            Dob.setVisible(true);
            Course.setVisible(true);
            Usertype.setVisible(true);
            NameL.setVisible(true);
            SexL.setVisible(true);
            DobL.setVisible(true);
            CourseL.setVisible(true);
            UsertypeL.setVisible(true);
            Separator.setVisible(true);
            Update.setVisible(true);
            FeesorsalL.setVisible(true);
            Feesorsal.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Viewuser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ShowdetailsActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Help.setVisible(false);
        UserID.setEditable(true);
        PasswordL.setVisible(false);
        Password.setVisible(false);
        Separator2.setVisible(false);
        UserID.setText("");
        DetailsL.setVisible(false);
        Name.setVisible(false);
        Sex.setVisible(false);
        Dob.setVisible(false);
        Course.setVisible(false);
        Usertype.setVisible(false);
        Separator.setVisible(false);
        Update.setVisible(false);
        NameL.setVisible(false);
        SexL.setVisible(false);
        DobL.setVisible(false);
        CourseL.setVisible(false);
        UsertypeL.setVisible(false);
        FeesorsalL.setVisible(false);
        Feesorsal.setVisible(false);
        UserID.setEditable(true);
        Edit1.setVisible(false);
        Edit2.setVisible(false);
        Edit3.setVisible(false);
        Edit4.setVisible(false);
        Edit5.setVisible(false);
        Edit6.setVisible(false);
        Edit1.setEnabled(true);
        Edit2.setEnabled(true);
        Edit3.setEnabled(true);
        Edit4.setEnabled(true);
        Edit5.setEnabled(true);
    }//GEN-LAST:event_ResetActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","cam","project");
            Statement stat = con.createStatement();
            int monf;
            String fos="",name, flag="",userid, dt="",mon="",year="",dob="",dobf="", course="" ;
            char sex=' ', usertype,temp=' ';
            userid=UserID.getText();
            usertype=Usertype.getText().charAt(0);
            flag=Usertype.getText();
            if ( flag.equalsIgnoreCase("Student") || flag.equalsIgnoreCase("Admin") || flag.equalsIgnoreCase("Teacher") || flag.equalsIgnoreCase("Administrator")) {
            } else {
                JOptionPane.showMessageDialog(this,"Invalid User Type");
                return;
            }
            fos=Feesorsal.getText();
            name=Name.getText();
            dob=Dob.getText();
            for(int t=8;t<=9;t++) {
                temp=dob.charAt(t);
                dt += temp;
            }
            dobf=dt+"-";
            for(int t=5;t<=6;t++) {
                temp=dob.charAt(t);
                mon += temp;
            }
            if(mon.equals("08")) {
                dobf=dobf+"August-";
            } else if (mon.equals("09")) {
                dobf=dobf+"September-";
            }
            monf=Integer.parseInt(mon);
            switch(monf) {
                case 01 : dobf=dobf+"January-";
                    break;
                case 02 :dobf=dobf+"February-";
                    break;
                case 03 :dobf=dobf+"March-";
                    break;
                case 04 :dobf=dobf+"April-";
                    break;
                case 05 :dobf=dobf+"May-";
                    break;
                case 06 :dobf=dobf+"June-";
                    break;
                case 07 :dobf=dobf+"July-";
                    break;
                case 10 :dobf=dobf+"October-";
                    break;
                case 11 :dobf=dobf+"November-";
                    break;
                case 12 : dobf=dobf+"December-";
                    break;  
                default :    
            }
            for(int t=0;t<=3;t++) {
                temp=dob.charAt(t);
                year += temp;
            }
            dobf=dobf+year;
            course=Course.getText();
            sex=Sex.getText().charAt(0);
            flag=Sex.getText();
            if ( flag.equalsIgnoreCase("Male") || flag.equalsIgnoreCase("Female")) {
            } else {
                JOptionPane.showMessageDialog(this,"Invalid Gender Entered");
                return;
            }
            ResultSet rs=stat.executeQuery("select password from login where loginid='"+aduserid+"'");
            String dbapass="", passc="",adminpass="";
            int i=0;
            if (rs.next()) {
                dbapass=rs.getString(1);
            }
            int len = dbapass.length();
            passc="";
            while(i!=len) {
                temp = dbapass.charAt(i);
                temp=(char) ((int) temp-2);
                passc += temp;
                i++;
            }
            adminpass=new String(Password.getPassword());
            if(adminpass.equals(passc)) {
                stat.executeQuery("update login set loginid='"+userid+"',name='"+name+"',type='"+usertype+"' where loginid='"+userid+"'");
                stat.executeQuery("update details set courseanddept='"+course+"',sex='"+sex+"',dob='"+dobf+"',feesorsal='"+fos+"' where loginid='"+userid+"'");
                rs = stat.executeQuery("select comments from modifyinfo where loginid='"+userid+"' and status='P'");
                if (rs.next()) {
                   stat.executeQuery("update modifyinfo set status='C' where loginid='"+userid+"'");
                }
                JOptionPane.showMessageDialog(this,"User Updated");
                ResetActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this,"Wrong Admin Password");
            }        
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Updateuser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Admin ob=new Admin(""+aduserid,""+adname);
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        JOptionPane.showMessageDialog(this,"CompSci - Computer\nCivil - Civil\nMechanical - Mechanical\nECE - Electronics\nElectrical - Electrical");
    }//GEN-LAST:event_HelpActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
        Name.setEditable(true);
        Edit1.setEnabled(false);
    }//GEN-LAST:event_Edit1ActionPerformed

    private void Edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit2ActionPerformed
        Sex.setEditable(true);
        Edit2.setEnabled(false);
    }//GEN-LAST:event_Edit2ActionPerformed

    private void Edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit3ActionPerformed
        Usertype.setEditable(true);
        Edit3.setEnabled(false);
    }//GEN-LAST:event_Edit3ActionPerformed

    private void Edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit4ActionPerformed
        Dob.setEditable(true);
        Edit4.setEnabled(false);
    }//GEN-LAST:event_Edit4ActionPerformed

    private void Edit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit5ActionPerformed
        Course.setEditable(true);
        Edit5.setEnabled(false);
    }//GEN-LAST:event_Edit5ActionPerformed

    private void Edit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit6ActionPerformed
        JOptionPane.showMessageDialog(this,"To Be Updated In Accounts Section");
    }//GEN-LAST:event_Edit6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Course;
    private javax.swing.JLabel CourseL;
    private javax.swing.JLabel DetailsL;
    private javax.swing.JTextField Dob;
    private javax.swing.JLabel DobL;
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Edit2;
    private javax.swing.JButton Edit3;
    private javax.swing.JButton Edit4;
    private javax.swing.JButton Edit5;
    private javax.swing.JButton Edit6;
    private javax.swing.JTextField Feesorsal;
    private javax.swing.JLabel FeesorsalL;
    private javax.swing.JButton Help;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameL;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordL;
    private javax.swing.JButton Reset;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JTextField Sex;
    private javax.swing.JLabel SexL;
    private javax.swing.JButton Showdetails;
    private javax.swing.JButton Update;
    private javax.swing.JLabel UpdateuserL;
    private javax.swing.JTextField UserID;
    private javax.swing.JLabel UserIDL;
    private javax.swing.JTextField Usertype;
    private javax.swing.JLabel UsertypeL;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
